package com.bank.islamic.latepaymentcharityhandling;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Late Payment Charity Handling
 *
 * Business Area:      Islamic Financing
 * Business Domain:    Lease And Partnership Financing
 * Functional Pattern: Process
 * Asset Type:         Late Payment Charity Entry
 * Control Record:     Late Payment Charity Entry Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Late Payment Charity Handling — BIAN Semantic API")
                .description("Service Domain 'Late Payment Charity Handling' (Process pattern) "
                        + "operating on the 'Late Payment Charity Entry Procedure' control record.")
                .version("0.1.0"));
    }
}
